# Personal info
name: Hisham
title: Java Backend Coder 

# Social links
github_username:  Hisham-isaac
linkedin_username: hisham-isaac-299ab9180

about_profile_image: ![](https://imgur.com/a/LLFsoRn)
about_content: "I’m a self-professed geek, with a varied interest that includes; Technology, Entrepreneurship, Economics, Physical activity and nutrition, to mention a few. I would best be described as someone who’s incisively curious about life in general, however small or insignificant the element. I believe that this gives me a rounded approach to learning, and helps me to draw links and parallels between topics that have little in common in order to come up with innovative solution, when trying to solve larger complex problems."

  

Education Section:
Degree: "Bachelors in Economics."



# Footer
footer_show_references: true


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
https://imgur.com/H3Mzyli
